name: Ask Chotu

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 */2 * * *"

concurrency:
  group: Ask Chotu
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Initialize Go module
        run: go mod init ask-chotu
        
      - name: Download dependencies
        run: go mod tidy
        
      - name: Run server
        env:
          NTFY_TOPICS: ${{ secrets.NTFY_TOPICS }}
          GITHUB_TOKEN: ${{ secrets.MODEL_TOKEN }}
          GISTS: ${{ secrets.GISTS }}
        run: go run .
